# permissions for end users to view secretclaims.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secretclaim-viewer-role
rules:
- apiGroups:
  - secret-operator.io
  resources:
  - secretclaims
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - secret-operator.io
  resources:
  - secretclaims/status
  verbs:
  - get
