# permissions for end users to edit secretclaims.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secretclaim-editor-role
rules:
- apiGroups:
  - secret-operator.io
  resources:
  - secretclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - secret-operator.io
  resources:
  - secretclaims/status
  verbs:
  - get
