apiVersion: secret-operator.io/v1alpha1
kind: SecretClaim
metadata:
  name: kube-property-source
spec:
  kubernetes:
    name: password-dest
    namespace: default
    secretType: Opaque
    labels:
      app: custom
    annotations:
      do-not-delete: 'true'
    properties:
    - name: someHmacToken
      source:
        generator:
          hmac: true
    - name: somePassword
      source:
        generator:
          password:
            length: 20
