apiVersion: secret-operator.io/v1alpha1
kind: SecretClaim
metadata:
  name: set-of-secret-claims
spec:
  kubernetes:
    name: password-dest
    namespace: default
    secretType: Opaque
    labels:

    properties:
    - name: someHmacToken
      source:
        generator:
          hmac: true
    - name: somePassword
      source:
        generator:
          password:
            length: 20
