apiVersion: secret-operator.io/v1alpha1
kind: SecretStore
metadata:
  name: secretstore-azure
spec:
  provider:
    azureKeyVault:
      vaultName: cmv
      auth:
        useManagedIdentity: false
        subscriptionId:
          value: 6973a0e5-ce16-480c-935b-3f8aebf93f84
        tenantId:
          value: df8eac07-e025-4521-80e8-6b66838cb092
        clientId:
          value: ba864fb9-403a-4549-b330-68d8de43a6c2
        clientSecret:
          value: ""
